server:
  port: 8080
  servlet:
    context-path: /recommendation

---
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    generate-ddl: on
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vehiclerecommendation?useSSL=false&serverTimezone=UTC
    username: root
    password: admin
